version: 2.1

executors:
  go:
    working_directory: /go/src/github.com/hashicorp/nomad
    environment:
      GOPATH: /go
    docker:
      # go1.11 uses a lot of ram when linking... rolling back to 1.10 for now.
      - image: golang:1.10
        user: root

jobs:
  build:
    executor: go
    steps:
      - checkout
      - run: make bootstrap
      - run: make check
      - run: make dev
  test:
    executor: go
    steps:
      - checkout
      - run: make bootstrap
      - setup_remote_docker
      - run: make test-nomad
  build-website:
    # setting the working_directory along with the checkout path allows us to not have
    # to cd into the website/ directory for commands
    working_directory: ~/project/website
    docker:
      - image: hashicorp/middleman-hashicorp:0.3.35
    steps:
      - checkout:
          path: ~/project

      # restores gem cache
      - restore_cache:
          key: static-site-gems-v1-{{ checksum "Gemfile.lock" }}

      - run:
          name: install gems
          command: bundle check || bundle install --path vendor/bundle --retry=3

      # saves gem cache if we have changed the Gemfile
      - save_cache:
          key: static-site-gems-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/project/website/vendor/bundle

      - run:
          name: middleman build
          command: bundle exec middleman build

      - run:
          name: website deploy
          command: ./scripts/deploy.sh

workflows:
  version: 2
  dev:
    jobs:
      - build
      - test
  website:
    jobs:
      - build-website:
          context: static-sites
          filters:
            branches:
              only: stable-website
